### ISSUE TITLE
Dragging of marker drops coordinates.

### ISSUE THREAD

**Issue by alapaev** [Sterc/mapsTv#10]
Maps TV v 1.0.1. I've entered addres, clicked on button "generate..." and got latititude and longtitude values. Then I dragged marker into another position.

Latititude after that contains string "function() {return a;}" and longtitude contains string "function() {return b;}"

What have I done wrong way?

**Comment by tazeverywhere** [comment]
Hello,
same version, same behavior...
it's strange, because it was working last week and I did not update anything.. 
@alapaev did you find a way ?

**Comment by jenswittmann** [comment]
Look here: https://github.com/Sterc/mapsTv/issues/12

**Comment by MrRoco** [comment]
Fixed with #13
