### ISSUE TITLE
Bug: Maps Crash

### ISSUE THREAD

**Issue by jenswittmann** [Sterc/mapsTv#12]
hello,
i got an error if i move the marker and reload the modx resource. do you have an idea to fix it?
maybe there is an error on this line:

``Ext.getCmp('mapstv'+config.tvId+'-longitude').setValue(LatLng[Object.keys(LatLng)[1]]);``

video for reproducing the bug: http://quick.as/pzrdtbaa5

thanks a lot
jens

**Comment by jenswittmann** [comment]
I think this works: https://github.com/Sterc/mapsTv/pull/13

**Comment by MrRoco** [comment]
Solved in issue #13
